package io.github.akakishi04.asobibatweaks.feature;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;

/** Specialize only the bonus generated by the actual Fortune loot function. */
public final class FortuneMasteryService {
    private FortuneMasteryService() {}

    public static boolean hasBranch(LootContext context) {
        ItemStack tool = context.getParamOrNull(LootContextParams.TOOL);
        return tool != null && LauncherReloadMasteryEvents.branch(tool, "minecraft:fortune") != null;
    }

    public static int adjust(int baseline, int generated, LootContext context) {
        ItemStack tool = context.getParamOrNull(LootContextParams.TOOL);
        var branch = tool == null ? null : LauncherReloadMasteryEvents.branch(tool, "minecraft:fortune");
        if (branch == null || generated <= baseline) return generated;
        BlockState state = context.getParamOrNull(LootContextParams.BLOCK_STATE);
        if (state == null) return generated;
        String block = BuiltInRegistries.BLOCK.getKey(state.getBlock()).getPath();
        boolean approved = branch.choice() == 0 ? block.endsWith("_ore")
                : branch.choice() != 1 || isHarvest(block);
        if (!approved) return generated;
        return adjustBonus(baseline, generated, branch.choice(), branch.progress(), context.getRandom());
    }

    static int adjustBonus(int baseline, int generated, int branch, double progress, RandomSource random) {
        long bonus = Math.max(0L, (long)generated - baseline);
        if (bonus == 0) return generated;
        double growth = Math.max(0.0D, Math.min(1.0D, progress));
        if (branch == 0 || branch == 1) {
            return random.nextFloat() < 0.10D + 0.15D * growth
                    ? (int)Math.min(Integer.MAX_VALUE, (long)generated + 1L) : generated;
        }
        if (branch != 2 || random.nextFloat() >= 0.10D + 0.20D * growth) return generated;
        // The volatile outcome removes or doubles ONLY the real bonus. Its
        // two equally likely outcomes preserve expected count and all base drops.
        return random.nextBoolean()
                ? (int)Math.min(Integer.MAX_VALUE, (long)baseline + bonus * 2L) : baseline;
    }

    private static boolean isHarvest(String block) {
        return "wheat".equals(block) || "carrots".equals(block) || "potatoes".equals(block)
                || "beetroots".equals(block) || "nether_wart".equals(block)
                || "sweet_berry_bush".equals(block) || "cocoa".equals(block)
                || "melon".equals(block) || block.endsWith("_leaves");
    }
}
